### PR TITLE
Ignoring `yoda` expressions

### PR DESCRIPTION
**Pull request by ryanrath**
Per convo w/ @plessbd

### CODE REVIEW

**Comment by smgallo** [comment]
Yes, I like using "yoda"  expressions.

**Comment by smgallo** [comment]
Does `"yoda": "off"` actually turn off checking of yoda expressions? That's not a valid value according to https://eslint.org/docs/rules/yoda or are we on an older version?

**Comment by ryanrath** [comment]
I saw that as well when I was working on the change. But noticed that some of the other entries that had `"off"` specified also did not mention it being one of the values. Such as, `"func-names"` https://eslint.org/docs/rules/func-names#require-or-disallow-named-function-expressions-func-names

After a quick check it does seem to be working ( or not working? ) as expected. As an example, I checked out my xdmod branch `fix-user-admin-email` that has some yoda expressions in it. Removed the `"yoda": "off"` property and ran the style check, it errored as expected, after re-adding the property and re-running the style check the branch got a clean bill of health.

**Review by smgallo — APPROVED** [review]
I like yoda because I'm an old C programmer.

**Pull request merged**
